import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Terminal } from "lucide-react";
import { AuditReport } from "@/components/AuditReport";
import { getSharedAudit } from "@/lib/audits.functions";

export const Route = createFileRoute("/share/$token")({
  head: () => ({
    meta: [
      { title: "Shared audit report — ScaleCheck" },
      { name: "description", content: "A shared scale readiness report generated by ScaleCheck." },
      { property: "og:title", content: "Shared audit report — ScaleCheck" },
      {
        property: "og:description",
        content: "A shared scale readiness report generated by ScaleCheck.",
      },
    ],
  }),
  component: SharedAudit,
});

function SharedAudit() {
  const { token } = Route.useParams();
  const fetchShared = useServerFn(getSharedAudit);
  const { data, isLoading, error } = useQuery({
    queryKey: ["shared", token],
    queryFn: () => fetchShared({ data: { token } }),
    retry: false,
  });

  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border/60">
        <div className="mx-auto flex h-14 max-w-5xl items-center justify-between px-4">
          <Link to="/" className="flex items-center gap-2 font-mono text-sm font-semibold">
            <Terminal className="size-4 text-primary" /> scalecheck
          </Link>
          <Link
            to="/auth"
            className="font-mono text-xs text-muted-foreground hover:text-foreground"
          >
            Run your own audit →
          </Link>
        </div>
      </header>
      <div className="mx-auto max-w-5xl px-4 py-10">
        {isLoading && <p className="font-mono text-xs text-muted-foreground">loading report…</p>}
        {error && (
          <p className="font-mono text-xs text-critical">
            This shared audit link is no longer valid.
          </p>
        )}
        {data && <AuditReport audit={data.audit} issues={data.issues} />}
      </div>
    </div>
  );
}
